### ISSUE TITLE
Nignx 1.24.0 ‘ngx_http_headers_in_t’ has no member named ‘cookies’

### ISSUE THREAD

**Issue by NayanTank2** [nginxinc/docker-nginx#783]
Dear Team,

I am trying to compile Nginx 1.24.0 latest stable version. During Header module facing same issue. I have noticed few blogs where issue is fixed in 1.23.1 but that binary is not available. I need to use 1.24.0 only so kindly suggest me how can I fix this issue.

        -o objs/addon/src/ngx_http_headers_more_headers_in.o \
        /app/middleware/nginx/binary/headers-more-nginx-module-master//src/ngx_http_headers_more_headers_in.c
In file included from /usr/include/dlfcn.h:25:0,
                 from src/os/unix/ngx_linux_config.h:58,
                 from src/core/ngx_config.h:26,
                 from /app/middleware/nginx/binary/headers-more-nginx-module-master//src/ddebug.h:5,
                 from /app/middleware/nginx/binary/headers-more-nginx-module-master//src/ngx_http_headers_more_headers_in.c:10:
/app/middleware/nginx/binary/headers-more-nginx-module-master//src/ngx_http_headers_more_headers_in.c:162:18: error: ‘ngx_http_headers_in_t’ has no member named ‘cookies’
                  **offsetof(ngx_http_headers_in_t, cookies),**

**Comment by thresheek** [comment]
Hi @NayanTank2,

You need to upgrade headers-more module to the latest version to be able to build it with nginx 1.24.0.

**Comment by NayanTank2** [comment]
I have already downloaded upgraded header module. But still facing the same issue. I check it doesn't support 1.24 version. Do you have supported header module link ? Please share.

**Comment by NayanTank2** [comment]
As per below link 

https://github.com/openresty/headers-more-nginx-module#compatibility

Still it doesn't support stable version of 1.24.

Compatibility
The following versions of Nginx should work with this module:

1.21.x (last tested: 1.21.4)
1.19.x (last tested: 1.19.9)
1.17.x (last tested: 1.17.8)
1.16.x
1.15.x (last tested: 1.15.8)
1.14.x
1.13.x (last tested: 1.13.6)
1.12.x
1.11.x (last tested: 1.11.2)
1.10.x
1.9.x (last tested: 1.9.15)
1.8.x
1.7.x (last tested: 1.7.10)
1.6.x (last tested: 1.6.2)
1.5.x (last tested: 1.5.8)
1.4.x (last tested: 1.4.4)
1.3.x (last tested: 1.3.7)
1.2.x (last tested: 1.2.9)
1.1.x (last tested: 1.1.5)
1.0.x (last tested: 1.0.11)
0.9.x (last tested: 0.9.4)
0.8.x (last tested: 0.8.54)
0.7.x >= 0.7.44 (last tested: 0.7.68)

**Comment by thresheek** [comment]
The latest version from the link you provided is known to compile fine with 1.24.0/1.25.0
